### ISSUE TITLE
exportStates does not escape </script> tags

### ISSUE THREAD

**Issue by LukasBombach** [Akryum/vue-apollo#410] opened 2018-10-09 13:33 UTC
Hey,

we have embeds in our Apollo state. Some of these embeds contain `</script>` tags. We use

```js
context.renderApolloState = () => `<script>${apolloProvider.exportStates()}</script>`;
```

to render the Apollo state from our SSR-server to the client. Now the `</script>` (ending script) string will be rendered plainly to the html which means the `<script>` (beginning script of apollo state) stops and the rest of the Apollo state gets rendered as text to our website.

It'd be cool if `exportStates` would escape  `</script>`

**Comment by Akryum** [comment] 2019-01-09 09:45
Duplicate of #158

**Closed by Akryum** 2019-01-09 09:45 UTC
Labels: enhancement
