### ISSUE TITLE
Generic type 'FetchMoreQueryOptions<TVariables, TData>' requires between 1 and 2 type arguments.

### ISSUE THREAD

**Issue by scratchmex** [Akryum/vue-apollo#1260] opened 2021-09-08 19:13 UTC
**Describe the bug**
A clear and concise description of what the bug is:

Bare new vite app and trying to use `@vue/apollo-composable`

**To Reproduce**
1. run `yarn build`

```console
❯ yarn build
yarn run v1.22.4
warning package.json: No license field
$ vue-tsc --noEmit && vite build
node_modules/@vue/apollo-composable/dist/useLazyQuery.d.ts:18:54 - error TS2707: Generic type 'FetchMoreQueryOptions<TVariables, TData>' requires between 1 and 2 type arguments.

18     fetchMore: <K extends keyof TVariables>(options: import("@apollo/client/core").FetchMoreQueryOptions<TVariables, K, any> & import("@apollo/client/core").FetchMoreOptions<TResult, TVariables>) => Promise<import("@apollo/client/core").ApolloQueryResult<TResult>> | undefined;
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

**Expected behavior**

**Versions**
vue: 3.2.10
@vue/apollo-composable: 4.0.0-alpha.14
@apollo/client: 3.4.10

**Additional context**

**Comment by zorji** [comment] 2021-09-18 08:08
I found that it's a change in `@apollo/client` 3.4

In v3.3, it still accepts 3 type params. See https://github.com/apollographql/apollo-client/blob/v3.3.0/src/core/watchQueryOptions.ts#L38

This command can fix the issue
```
npm i -S @apollo/client@3.3
```

**Comment by Akryum** [comment] 2021-09-20 16:13
Duplicate of #1252

**Closed as completed by Akryum** 2021-09-20 16:13 UTC
