### ISSUE TITLE
TypeError: config is null

### ISSUE THREAD

**Issue by jawittdesigns** [Akryum/vue-apollo#641] opened 2019-06-01 03:58 UTC
I created a new Vue.js app and added vue-apollo via `vue add apollo`

After starting my app I'm getting a white screen of death and there is a error in the console 

```
TypeError: config is null
  InMemoryCache bundle.esm.js:863
  createApolloClient index.js:76
  createProvider vue-apollo.js:60
  <anonymous> main.js:28
  js app.js:5385
  __webpack_require__ app.js:767
  fn app.js:130
  0 app.js:5471
  __webpack_require__ app.js:767
  <anonymous> app.js:902
  <anonymous> app.js:905
```

If I remove `apolloProvider: createProvider(),` from the `new Vue()` instance the app works.

It's all a base install with no modifications to the code and I can't find anything in the docs about a `config`

Am I missing some type of configuration that's not documented in the docs?

**Update**

The `TypeError: config is null` was the error I got while using Firefox. I opened my app in Chrome and got this error.

`Cannot read property 'freezeResults' of null`

I searched the issues and found this issue https://github.com/Akryum/vue-apollo/issues/631

It has a solution that got my app working, but it doesn't feel ideal. It seems like there is a bug in apollo-cache-inmemory or Vue Apollo needs to update the default vue-apollo.js config file.

**Comment by Tarabass** [comment] 2019-06-16 12:36
I just ran into this error as well. As my first attempt of using vue-apollo it doesn't feel convenient .

vue-cli: v3.8.4
vue: v2.6.10
vue-apollo: v3.0.0-beta.11

To reproduce just create a new Vue project with the cli, add vue-apollo and start both apollo and the app.

**Comment by Akryum** [comment] 2019-09-30 11:33
Duplicate of #630

**Closed by Akryum** 2019-09-30 11:33 UTC
