### ISSUE TITLE
your example do not work in china net

### ISSUE THREAD

**Issue by ssw1992** [Akryum/vue-apollo#785] opened 2019-09-19 08:57 UTC
https://jsfiddle.net/Akryum/oyejk2qL/

![image](https://user-images.githubusercontent.com/24841397/65229043-293e2e00-dafe-11e9-8417-2c5f356085d6.png)

I am a new user of vue-apollo,so if it work ,it will be easy for me to understand the features of vue-apollo.

**Comment by Akryum** [comment] 2019-09-19 10:37
Duplicate of #634

**Closed by Akryum** 2019-09-19 10:37 UTC
