### ISSUE TITLE
Package warning 

### ISSUE THREAD

**Issue by shtse8** [Akryum/vue-apollo#133] opened 2017-10-25 10:05 UTC
```
warning "vue-apollo@2.1.0-rc.8" has incorrect peer dependency "apollo-client@^1.0.1".
```
It seems apollo-client is upgraded to 2.0.1 while vue-apollo is still requiring the old version.
also, the documentation is already out of day for the latest apollo-client.

**Comment by Akryum** [comment] 2017-10-25 10:09
Duplicate of #117

**Closed by Akryum** 2017-10-25 10:09 UTC
