### ISSUE TITLE
How to including header vue-apollo

### ISSUE THREAD

**Issue by phakphumi** [Akryum/vue-apollo#182] opened 2018-01-12 19:13 UTC
I would like to send token to server via headers.authorization

the problem is I have no idea how to include headers in vue-apollo

**Comment by kieusonlam** [comment] 2018-01-15 07:49
@phakphumi you can take a look at this https://github.com/Akryum/vue-apollo/issues/144

**Comment by Akryum** [comment] 2018-02-11 21:13
Duplicate of #144

**Closed** 2018-02-11 21:13 UTC
